// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'AntDesign:alipayCircleOutlined': typeof import('~icons/ant-design/alipay-circle-outlined')['default']
    'AntDesign:caretLeftOutlined': typeof import('~icons/ant-design/caret-left-outlined')['default']
    'AntDesign:caretRightOutlined': typeof import('~icons/ant-design/caret-right-outlined')['default']
    'Carbon:3dPrintMesh': typeof import('~icons/carbon/3d-print-mesh')['default']
    'Carbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'Carbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'Carbon:batteryFull': typeof import('~icons/carbon/battery-full')['default']
    Carbon3dCursorAlt: typeof import('~icons/carbon/3d-cursor-alt')['default']
    CustomInput: typeof import('./../src/components/custom-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanSpace: typeof import('vant/es')['Space']
  }
}
